# ==============================================================================
# Reproducible synthetic data generator for tests.
#
# Deliberately NOT a simplified/closed-form simulation: event times are
# generated by numerically inverting the SAME time-dependent hazard
# (h(t) = h0(t) * exp(alpha * m_i(t)), m_i(t) = beta0 + b_i + beta1*t) that
# jmjax actually fits. A simpler simulation (e.g. alpha*b_i-only, which has
# a closed-form Weibull inverse) would risk tests passing even if the
# time-dependent term were implemented incorrectly - this generator can only
# pass if that term round-trips correctly.
# ==============================================================================

#' Simulate a longitudinal + survival dataset consistent with jmjax's model.
#'
#' @param n Number of subjects.
#' @param seed RNG seed, for reproducibility across test runs.
#' @param max_time Administrative censoring time.
#' @param visit_times Candidate longitudinal visit times (truncated per
#'   subject at their observed event/censoring time).
#' @return A list with data_long, data_surv, and the true generating
#'   parameters (for the "recovers truth" tests).
simulate_joint_data <- function(n = 200,
                                 seed = 123,
                                 beta0 = 2.0, beta1 = 0.5,
                                 sigma_b = 0.8, sigma_e = 0.3,
                                 weibull_shape = 1.2, log_lambda0 = -2.0,
                                 alpha = 0.6,
                                 max_time = 5,
                                 visit_times = seq(0, 5, by = 0.5)) {
  set.seed(seed)
  b <- stats::rnorm(n, 0, sigma_b)

  cum_hazard <- function(t, b_i) {
    if (t <= 0) return(0)
    integrand <- function(s) {
      h0 <- weibull_shape * s^(weibull_shape - 1) * exp(log_lambda0)
      m_s <- beta0 + b_i + beta1 * s
      h0 * exp(alpha * m_s)
    }
    stats::integrate(integrand, lower = 0, upper = t)$value
  }

  T_true <- vapply(seq_len(n), function(i) {
    u <- stats::runif(1)
    target <- -log(u)
    upper_bound <- max_time * 4
    if (cum_hazard(upper_bound, b[i]) < target) {
      return(Inf)  # would survive well past the censoring window anyway
    }
    stats::uniroot(function(t) cum_hazard(t, b[i]) - target,
                    lower = 1e-6, upper = upper_bound)$root
  }, numeric(1))

  obs_time <- pmin(T_true, max_time)
  event <- as.integer(T_true <= max_time)

  data_surv <- data.frame(id = seq_len(n), time = obs_time, event = event)

  long_rows <- lapply(seq_len(n), function(i) {
    vt <- visit_times[visit_times <= obs_time[i]]
    if (length(vt) == 0) vt <- 0
    y <- beta0 + b[i] + beta1 * vt + stats::rnorm(length(vt), 0, sigma_e)
    data.frame(id = i, time = vt, y = y)
  })
  data_long <- do.call(rbind, long_rows)

  list(
    data_long = data_long,
    data_surv = data_surv,
    truth = list(
      beta0 = beta0, beta1 = beta1, sigma_b = sigma_b, sigma_e = sigma_e,
      weibull_shape = weibull_shape, log_lambda0 = log_lambda0, alpha = alpha
    )
  )
}

#' Simulate with a GENUINE, correlated random intercept + slope (not just
#' intercept, unlike simulate_joint_data() above). Needed to properly test
#' random_effects = "intercept_slope" against real ground truth - forcing
#' that method onto slope-free data produces attenuation bias in alpha that
#' is a real statistical artifact (confirmed during development), not a
#' defect, and would make truth-recovery checks meaningless for this path.
simulate_joint_data_re2 <- function(n = 300, seed = 1,
                                     beta0 = 2.0, beta1 = 0.5,
                                     sigma_b0 = 0.8, sigma_b1 = 0.2, rho = 0.3,
                                     sigma_e = 0.3,
                                     weibull_shape = 1.2, log_lambda0 = -2.0,
                                     alpha = 0.6, max_time = 5,
                                     visit_times = seq(0, 5, by = 0.5)) {
  set.seed(seed)
  b0 <- stats::rnorm(n, 0, sigma_b0)
  b1 <- rho * (sigma_b1 / sigma_b0) * b0 + sqrt(1 - rho^2) * sigma_b1 * stats::rnorm(n)

  cum_hazard <- function(t, b0_i, b1_i) {
    if (t <= 0) return(0)
    integrand <- function(s) {
      h0 <- weibull_shape * s^(weibull_shape - 1) * exp(log_lambda0)
      m_s <- (beta0 + b0_i) + (beta1 + b1_i) * s
      h0 * exp(alpha * m_s)
    }
    stats::integrate(integrand, lower = 0, upper = t)$value
  }

  T_true <- vapply(seq_len(n), function(i) {
    target <- -log(stats::runif(1))
    ub <- max_time * 4
    if (cum_hazard(ub, b0[i], b1[i]) < target) return(Inf)
    stats::uniroot(function(t) cum_hazard(t, b0[i], b1[i]) - target, lower = 1e-6, upper = ub)$root
  }, numeric(1))

  obs_time <- pmin(T_true, max_time)
  event <- as.integer(T_true <= max_time)
  data_surv <- data.frame(id = seq_len(n), time = obs_time, event = event)

  long_rows <- lapply(seq_len(n), function(i) {
    vt <- visit_times[visit_times <= obs_time[i]]
    if (length(vt) == 0) vt <- 0
    y <- (beta0 + b0[i]) + (beta1 + b1[i]) * vt + stats::rnorm(length(vt), 0, sigma_e)
    data.frame(id = i, time = vt, y = y)
  })
  data_long <- do.call(rbind, long_rows)

  list(
    data_long = data_long, data_surv = data_surv,
    truth = list(beta0 = beta0, beta1 = beta1, sigma_b0 = sigma_b0,
                 sigma_b1 = sigma_b1, rho = rho, sigma_e = sigma_e, alpha = alpha)
  )
}

#' Simulate data under a hazard that depends on BOTH value(t) and delta(t),
#' with distinct true alpha_value/alpha_delta coefficients - needed to
#' genuinely test functional_forms = ~ value(y) + delta(y), since simply
#' refitting old value-only data with the new option wouldn't exercise the
#' delta channel's contribution to the DATA-GENERATING process at all.
simulate_joint_data_delta <- function(n = 300, seed = 1,
                                       beta0 = 2.0, beta1 = 0.5, sigma_b = 0.8, sigma_e = 0.3,
                                       weibull_shape = 1.2, log_lambda0 = -2.0,
                                       alpha_value = 0.5, alpha_delta = 0.3,
                                       max_time = 5, visit_times = seq(0, 5, by = 0.5)) {
  set.seed(seed)
  b <- stats::rnorm(n, 0, sigma_b)

  cum_hazard <- function(t, b_i) {
    if (t <= 0) return(0)
    integrand <- function(s) {
      h0 <- weibull_shape * s^(weibull_shape - 1) * exp(log_lambda0)
      value_s <- beta0 + b_i + beta1 * s
      delta_s <- beta1 * s  # delta(s) = value(s) - value(0); intercept+b_i cancel for q=1
      h0 * exp(alpha_value * value_s + alpha_delta * delta_s)
    }
    stats::integrate(integrand, lower = 0, upper = t)$value
  }

  T_true <- vapply(seq_len(n), function(i) {
    u <- stats::runif(1)
    target <- -log(u)
    upper_bound <- max_time * 4
    if (cum_hazard(upper_bound, b[i]) < target) return(Inf)
    stats::uniroot(function(t) cum_hazard(t, b[i]) - target,
                    lower = 1e-6, upper = upper_bound)$root
  }, numeric(1))

  obs_time <- pmin(T_true, max_time)
  event <- as.integer(T_true <= max_time)
  data_surv <- data.frame(id = seq_len(n), time = obs_time, event = event)

  long_rows <- lapply(seq_len(n), function(i) {
    vt <- visit_times[visit_times <= obs_time[i]]
    if (length(vt) == 0) vt <- 0
    y <- beta0 + b[i] + beta1 * vt + stats::rnorm(length(vt), 0, sigma_e)
    data.frame(id = i, time = vt, y = y)
  })
  data_long <- do.call(rbind, long_rows)

  list(
    data_long = data_long, data_surv = data_surv,
    truth = list(beta0 = beta0, beta1 = beta1, sigma_b = sigma_b, sigma_e = sigma_e,
                 alpha_value = alpha_value, alpha_delta = alpha_delta)
  )
}

#' Simulate data under a hazard that depends on BOTH value(t) and area(t),
#' with distinct true alpha_value/alpha_area coefficients.
simulate_joint_data_area <- function(n = 300, seed = 1,
                                      beta0 = 2.0, beta1 = 0.5, sigma_b = 0.8, sigma_e = 0.3,
                                      weibull_shape = 1.2, log_lambda0 = -2.0,
                                      alpha_value = 0.4, alpha_area = 0.2,
                                      max_time = 5, visit_times = seq(0, 5, by = 0.5)) {
  set.seed(seed)
  b <- stats::rnorm(n, 0, sigma_b)

  cum_hazard <- function(t, b_i) {
    if (t <= 0) return(0)
    integrand <- function(s) {
      h0 <- weibull_shape * s^(weibull_shape - 1) * exp(log_lambda0)
      value_s <- beta0 + b_i + beta1 * s
      # area(s) = integral_0^s (beta0 + b_i + beta1*u) du = (beta0+b_i)*s + beta1*s^2/2
      area_s <- (beta0 + b_i) * s + beta1 * s^2 / 2
      h0 * exp(alpha_value * value_s + alpha_area * area_s)
    }
    stats::integrate(integrand, lower = 0, upper = t)$value
  }

  T_true <- vapply(seq_len(n), function(i) {
    u <- stats::runif(1)
    target <- -log(u)
    upper_bound <- max_time * 4
    if (cum_hazard(upper_bound, b[i]) < target) return(Inf)
    stats::uniroot(function(t) cum_hazard(t, b[i]) - target,
                    lower = 1e-6, upper = upper_bound)$root
  }, numeric(1))

  obs_time <- pmin(T_true, max_time)
  event <- as.integer(T_true <= max_time)
  data_surv <- data.frame(id = seq_len(n), time = obs_time, event = event)

  long_rows <- lapply(seq_len(n), function(i) {
    vt <- visit_times[visit_times <= obs_time[i]]
    if (length(vt) == 0) vt <- 0
    y <- beta0 + b[i] + beta1 * vt + stats::rnorm(length(vt), 0, sigma_e)
    data.frame(id = i, time = vt, y = y)
  })
  data_long <- do.call(rbind, long_rows)

  list(
    data_long = data_long, data_surv = data_surv,
    truth = list(beta0 = beta0, beta1 = beta1, sigma_b = sigma_b, sigma_e = sigma_e,
                 alpha_value = alpha_value, alpha_area = alpha_area)
  )
}

#' Simulate data under a hazard that depends on BOTH value(t) and
#' area_avg(t) = area(t)/t, with distinct true alpha_value/alpha_area_avg
#' coefficients - matches JMbayes2's actual area() convention (confirmed
#' by direct inspection of a fitted JMbayes2 object during development).
simulate_joint_data_area_avg <- function(n = 300, seed = 1,
                                          beta0 = 2.0, beta1 = 0.5, sigma_b = 0.8, sigma_e = 0.3,
                                          weibull_shape = 1.2, log_lambda0 = -2.0,
                                          alpha_value = 0.4, alpha_area_avg = 0.5,
                                          max_time = 5, visit_times = seq(0, 5, by = 0.5)) {
  set.seed(seed)
  b <- stats::rnorm(n, 0, sigma_b)

  cum_hazard <- function(t, b_i) {
    if (t <= 0) return(0)
    integrand <- function(s) {
      h0 <- weibull_shape * s^(weibull_shape - 1) * exp(log_lambda0)
      value_s <- beta0 + b_i + beta1 * s
      # area_avg(s) = area(s)/s = (beta0+b_i) + beta1*s/2
      area_avg_s <- (beta0 + b_i) + beta1 * s / 2
      h0 * exp(alpha_value * value_s + alpha_area_avg * area_avg_s)
    }
    stats::integrate(integrand, lower = 0, upper = t)$value
  }

  T_true <- vapply(seq_len(n), function(i) {
    u <- stats::runif(1)
    target <- -log(u)
    upper_bound <- max_time * 4
    if (cum_hazard(upper_bound, b[i]) < target) return(Inf)
    stats::uniroot(function(t) cum_hazard(t, b[i]) - target,
                    lower = 1e-6, upper = upper_bound)$root
  }, numeric(1))

  obs_time <- pmin(T_true, max_time)
  event <- as.integer(T_true <= max_time)
  data_surv <- data.frame(id = seq_len(n), time = obs_time, event = event)

  long_rows <- lapply(seq_len(n), function(i) {
    vt <- visit_times[visit_times <= obs_time[i]]
    if (length(vt) == 0) vt <- 0
    y <- beta0 + b[i] + beta1 * vt + stats::rnorm(length(vt), 0, sigma_e)
    data.frame(id = i, time = vt, y = y)
  })
  data_long <- do.call(rbind, long_rows)

  list(
    data_long = data_long, data_surv = data_surv,
    truth = list(beta0 = beta0, beta1 = beta1, sigma_b = sigma_b, sigma_e = sigma_e,
                 alpha_value = alpha_value, alpha_area_avg = alpha_area_avg)
  )
}

#' q=2 (correlated random intercept+slope) analogs of the delta/area/
#' area_avg simulators above, for testing _fit_mle_q2_extra_channel().
#' channel = "delta", "area", or "area_avg".
simulate_joint_data_re2_channel <- function(channel = c("delta", "area", "area_avg"),
                                             n = 400, seed = 1,
                                             beta0 = 2.0, beta1 = 0.5,
                                             sigma_b0 = 0.8, sigma_b1 = 0.2, rho = 0.3,
                                             sigma_e = 0.3,
                                             weibull_shape = 1.2, log_lambda0 = -2.0,
                                             alpha_value = 0.4, alpha_extra = 0.3,
                                             max_time = 5, visit_times = seq(0, 5, by = 0.5)) {
  channel <- match.arg(channel)
  set.seed(seed)
  b0 <- stats::rnorm(n, 0, sigma_b0)
  b1 <- rho * (sigma_b1 / sigma_b0) * b0 + sqrt(1 - rho^2) * sigma_b1 * stats::rnorm(n)

  extra_fn <- switch(channel,
    delta = function(t, b0_i, b1_i) (beta1 + b1_i) * t,
    area = function(t, b0_i, b1_i) (beta0 + b0_i) * t + (beta1 + b1_i) * t^2 / 2,
    area_avg = function(t, b0_i, b1_i) (beta0 + b0_i) + (beta1 + b1_i) * t / 2
  )

  cum_hazard <- function(t, b0_i, b1_i) {
    if (t <= 0) return(0)
    integrand <- function(s) {
      h0 <- weibull_shape * s^(weibull_shape - 1) * exp(log_lambda0)
      value_s <- (beta0 + b0_i) + (beta1 + b1_i) * s
      extra_s <- extra_fn(s, b0_i, b1_i)
      h0 * exp(alpha_value * value_s + alpha_extra * extra_s)
    }
    stats::integrate(integrand, lower = 0, upper = t)$value
  }

  T_true <- vapply(seq_len(n), function(i) {
    u <- stats::runif(1)
    target <- -log(u)
    upper_bound <- max_time * 4
    if (cum_hazard(upper_bound, b0[i], b1[i]) < target) return(Inf)
    stats::uniroot(function(t) cum_hazard(t, b0[i], b1[i]) - target,
                    lower = 1e-6, upper = upper_bound)$root
  }, numeric(1))

  obs_time <- pmin(T_true, max_time)
  event <- as.integer(T_true <= max_time)
  data_surv <- data.frame(id = seq_len(n), time = obs_time, event = event)

  long_rows <- lapply(seq_len(n), function(i) {
    vt <- visit_times[visit_times <= obs_time[i]]
    if (length(vt) == 0) vt <- 0
    y <- (beta0 + b0[i]) + (beta1 + b1[i]) * vt + stats::rnorm(length(vt), 0, sigma_e)
    data.frame(id = i, time = vt, y = y)
  })
  data_long <- do.call(rbind, long_rows)

  list(
    data_long = data_long, data_surv = data_surv,
    truth = list(beta0 = beta0, beta1 = beta1, sigma_b0 = sigma_b0, sigma_b1 = sigma_b1,
                 rho = rho, sigma_e = sigma_e, alpha_value = alpha_value, alpha_extra = alpha_extra)
  )
}
